lab5/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from my_app.views import *
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin_url'),
    url(r'^$', RedirectView.as_view(url='/main/', permanent=False), name='index'),
    url(r'^main/$', main, name='main_url'),
    url(r'^db/$', db, name='db_url'),
    url(r'^books/$', books, name='books_url'),
    url(r'^reader/$', ReaderView.as_view(), name='reader_url'),
    url(r'^registration/$', registration, name='registration_url'),
    url(r'^registration2/$', registration2, name='registration2_url'),
    url(r'^login/$', login, name='login_url'),
    url(r'^success/$', success, name='success_url'),
    url(r'^logout/$', logout, name='logout_url'),
    url(r'^x0/$', x0, name='x0_url'),
    url(r'^list_books/(?P<id>\d+)', book_id, name='book_id_url'),
    url(r'^list_books/', ListBookView.as_view(), name='list_books_url'),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser


class Book(models.Model):
        id_book = models.AutoField(primary_key=True)
        name_book = models.CharField(max_length=100, verbose_name='Название книги')
        genre_book = models.CharField(max_length=50, default='Жанр неизвестен', verbose_name='Жанр')
        photo = models.ImageField(null=True, blank=True, default='no-image.png', verbose_name='Фото')
        writer_book = models.CharField(max_length=100, verbose_name='Автор')
        year_book = models.IntegerField(verbose_name='Год создания')
        users = models.ManyToManyField(User, through='Issuance', through_fields=('book_name', 'username'))

        def str(self):
            return '%s, %s' % (str(self.id_book), str(self.name_book))

        def get_users(self):
            return [{'name': user.username} for user in self.users.all()]

        class Meta:
            verbose_name_plural = "Книги"
            verbose_name = "Название книги"


class Issuance(models.Model):
    book_name = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name='Название книги')
    username = models.ForeignKey(User, on_delete=models.CASCADE)

    def str(self):
        return 'username:%s,  book_name:%s' % (str(self.username.username), str(self.book_name.name_book))

    class Meta:
        verbose_name_plural = "Выдачи"
        verbose_name = "Название книги"

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Библиотека</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static "images/book.png" %}" type="image/png">
    <link rel="stylesheet" href="{% static 'Bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'Bootstrap/css/font-awesome.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'Bootstrap/css/main.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'Bootstrap/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'Bootstrap/js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'Bootstrap/js/alight_0.12.last.min.js' %}"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                </button>
                <p1><img src="{% static "images/icon.png" %}" width="50" height="50"/></p1>
                <a class="navbar-brand" href="#">Библиотека</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'main_url' %}">На главную </a></li>
                    <li><a href="/admin/">Администрирование </a></li>
                    <li><a href="{% url 'db_url' %}">Списки</a></li>
                    <li>
                        <div class="dropdown">
                            <button class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{% static "images/login.png" %}" width="30" height="30" alt=""/>
                            </button>
                            <div class="dropdown-content">
                                {% if request.user.is_authenticated %}
                                    <span>Здравствуйте, {{ request.user.username }}</span>
                                    <a href="{% url 'logout_url' %}">Выйти</a>
                                {% else %}
                                    <a href="{% url 'login_url' %}">Вход</a>

                                    <a href="{% url 'registration2_url' %}">Регистрация</a>
                                {% endif %}
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    {% block body1 %}{% endblock %}
</body>
</html>

templates/book_id.html
{% extends 'base.html' %}

{% block body1 %}
<div id="header1">
        <div class="container">
            <div class="row centered">
                <div class="col-lg-8 col-lg-offset-2">
                    <h1 style="font-size: 60px"><br>{{ book.name_book }}<br></h1>
                    {% if book.photo %}
                                <td><img src="{{book.photo.url}}" width="300" height="300"></td>
                            {% endif %}
                    <table class="table table-hover table-inverse">
                        <tr href="{% url 'list_books_url'%}">
                            <td>Название</td>
                            <td>Жанр</td>
                            <td>Автор</td>
                            <td>Читатели</td>
                        </tr>
                        <tr>
                            <td>{{book.name_book}}</td>
                            <td>{{book.genre_book}}</td>
                            <td>{{book.writer_book}}</td>
                            <td>
                                {% for user in book.get_users %}
                                  <h4>{{ user.name }}</h4>
                                {% endfor %}
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
</div>
{% endblock %}

templates/books.html
{% extends 'base.html' %}

{% block body1 %}
    <div id="header1">
        <div class="container">
            <div class="row centered">
                <div class="col-lg-8 col-lg-offset-2">
                    <h1><br>Таблица книги<br></h1>
                    <form action="" enctype="multipart/form-data" method="post">{% csrf_token %}
                    <div class="input.#id-photo" style="margin-left: 50%"></div>
                    {{ form.as_p }}
                            <button type="submit" class="btn ui-button-icon-primary">
                                Добавить
                            </button>
                    </form>
                </div>
            </div>
            <button type="button" class="btn ui-button-icon-primary" data-toggle="modal" data-target="#myModal">Модалка</button>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <div id="myModal" class="modal fade" role="dialog">
      <div class="modal-dialog">
          <div class="modal-dialog" style="width: 400px">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h2 class="modal-title" style="font-size: 30px">Добавление новой книги</h2>
                        </div>
                        <div class="modal-body">
                            <form method="POST" enctype="multipart/form-data">
                                <div class="add-form container">
                                    {% csrf_token %}
                                    <div class="course_add">
                                        <label for="id_name_book">Название книги:</label>
                                        <div class="data-and-error">
                                            <input type="text" name="name_book" maxlength="100" required
                                                   id="id_name_book"/>
                                        </div>
                                    </div>
                                    <div class="course_add">
                                        <label for="id_genre_book">Жанр:</label>
                                        <div class="data-and-error">
                                            <input type="text" name="genre_book" maxlength="100" required
                                                   id="id_genre_book"/>
                                        </div>
                                    </div>
                                    <div class="course_add">
                                        <label for="id_photo">Фото:</label>
                                        <div class="data-and-error">
                                            <input type="file" name="photo" id="id_photo"/>
                                        </div>
                                    </div>
                                    <div class="course_add">
                                        <label for="id_writer_book">Автор:</label>
                                        <div class="data-and-error">
                                            <input type="text" name="writer_book" maxlength="100" required
                                                   id="id_genre_book"/>
                                        </div>
                                    </div>
                                    <div class="course_add">
                                        <label for="id_year_book">Год написания:</label>
                                        <div class="data-and-error">
                                            <input type="text" name="year_book" maxlength="100" required
                                                   id="id_year_book"/>
                                        </div>
                                    </div>
                                    <br><button type="submit" id="btn_add" style="margin-left: 5%">Добавить книгу</button>
                                    <br>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                        </div>
                    </div>
          </div>
      </div>
    </div>
{% endblock %}

templates/db.html
{% extends 'base.html' %}

{% block body1 %}
    <div id="header1">
        <div class="container">
            <div class="row centered">
                <div class="col-lg-8 col-lg-offset-2">
                    <h1><br><br>Сущности</h1>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="col-lg-8 col-lg-offset-2">
                <li><a href="{% url 'list_books_url' %}">Книги</a></li>
                <li><a href="{% url 'reader_url' %}">Читатели</a></li>
            </div>
        </div>
    </div>
{% endblock %}

templates/list_books.html
{% extends 'base.html' %}
{% block body1 %}
<div id="header1">
    <div class="container">
            <div class="row centered">
                <div class="col-lg-8 col-lg-offset-2">
                    <h1 style="font-size: 60px">Книги</h1>
                <div al-app  al-init="count=5" @scroll.debounce-50="($element.scrollTop > $element.scrollHeight - $element.clientHeight - 150)?count++:0" class="body">
                <div al-repeat="n in count">
                {% for Book in object_list %}
                    <div class="infinite-container">
                    <div class="infinite-item">
                    <tr>
                        <td> <a href="{% url 'book_id_url' Book.id_book%}">{{Book.name_book}} </a></td>
                        {% if Book.photo %}
                        <td><img src="{{Book.photo.url}}" width="350" height="300"></td>
                        {% endif %}
                    </tr>
                    </div>
                    </div>
                {% endfor %}
                </div>
            </div>
{#        {% if is_paginated %}#}
{#                <div class="pagination" style="font-size: 50px">#}
{#                    <span class="page-links">#}
{#                        {% if page_obj.has_previous %}#}
{#                            <a class="aquo" href="/list_books?page={{ page_obj.previous_page_number }}" style="color: yellow">&laquo;</a>#}
{#                        {% else %}#}
{#                            <span class="unavailable" href="" style="color: white">&laquo;</span>#}
{#                        {% endif %}#}
{#                        {% for page in page_obj.paginator.page_range %}#}
{#                            {% if page %}#}
{#                                {% ifequal page page_obj.number %}#}
{#                                    <span class="current-page" href="" style="color: white">{{ page }}</span>#}
{#                                {% else %}#}
{#                                    <a href="/list_books?page={{ page }}" class="page" style="color: yellow">{{ page }}</a>#}
{#                                {% endifequal %}#}
{#                            {% endif %}#}
{#                        {% endfor %}#}
{#                        {% if page_obj.has_next %}#}
{#                            <a class="aquo" href="/list_books?page={{ page_obj.next_page_number }}" style="color: yellow">&raquo;</a>#}
{#                        {% else %}#}
{#                            <span class="unavailable" href="" style="color: white">&raquo;</span>#}
{#                        {% endif %}#}
{#                        <span hidden id="per-page">{{ page_obj.paginator.per_page }}</span>#}
{#                    </span>#}
{#                </div>#}
{#            {% endif %}#}



  </div>
</div>
        </div>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block body1 %}
    <div id="body1">
        <div class="container">
            <div class="row centered">
                <div class="col-lg-8 col-lg-offset-2">
                    <h6><br>Авторизация<br><br></h6>
                </div>
            <form method="POST">
            <div class="auth_block"style="width: 352px">
                {% csrf_token %}
                <div class="auth_blank">
                    <label class="login" style="width: 60px">
                        Логин
                    </label>
                    <div class="form-block">
                        <input type="text" name="username">
                    </div>
                </div>
                <div class="auth_blank">
                    <label class="login" style="width: 70px">
                        Пароль
                    </label>
                    <div class="form-block">
                        <input type="password" name="password">
                    </div>
                </div>
                {% if error != "" %}
                    <p>{{ error }}</p>
                {% endif %}
                <br>
                <button type="submit">Войти</button>
            </div>
            </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/main.html
{% extends 'base.html' %}

{% block body1 %}

<link rel="stylesheet" href="http://bootstraptema.ru/snippets/slider/2016/cbpFWSlider/cbpFWSlider.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="http://bootstraptema.ru/snippets/slider/2016/cbpFWSlider/cbpFWSlider.min.js"></script>

<br><br><br>
<div class="container-fluid">
    <div class="row">
    {% load static %}
        <div class="col-xs-12">
            <div id="cbp-fwslider" class="cbp-fwslider">
               <ul>
                   <li><a href="{% url 'books_url' %}"><img src="{% static "images/addbook.jpg" %}"  style="  border-radius: 10%" alt="image 1"/></a></li>
                   <li><a href="{% url 'reader_url' %}"><img src="{% static "images/readers.jpg" %}"  style="  border-radius: 10%" alt="image 2"/></a></li>
               </ul>
            </div>
        </div>
    </div>
</div>

<script>
$( function() {
$( '#cbp-fwslider' ).cbpFWSlider();
});
</script>
{% endblock %}

templates/reader.html
{% extends 'base.html' %}

{% block body1 %}
    <div id="header1">
        <div class="container">
            <div class="row centered">
                <div class="col-lg-8 col-lg-offset-2">
                    <h1><br>Таблица читатели<br></h1>
                <table class="table table-hover table-inverse">
                <tr>
                    <th>Билет читателя</th>
                    <td>Имя</td>
                    <td>Фамилия</td>
                </tr>
                {% for User in object_list %}
                    <tr >
                        <th scope="row">{{User.id}}</th>
                        <td> {{User.first_name}} </td>
                        <td>{{User.last_name}}</td>
                    </tr>
                {% endfor %}
                </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/registration.html
{% extends 'base.html' %}

{% block body1 %}
    <div id="body1">
        <div class="container">
            <div class="row centered">
                <div class="col-lg-8 col-lg-offset-2">
                    <h5><br>Регистрация<br><br></h5>
                </div>
            <form method="POST">
            <div class="auth_block" style="width: 452px">
                {% csrf_token %}
                <div class="auth_blank">
                    <label>
                        Логин
                    </label>
                    <div class="form-block">
                        <input type="text" name="username" value="{{ username }}">
                        {% if errors.username != '' %}
                            <div class="form-error">{{ errors.username }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="auth_blank">
                    <label>
                        Пароль
                    </label>
                    <div class="form-block">
                        <input type="password" name="password">
                        {% if errors.password != '' %}
                            <div class="form-error">{{ errors.password }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="auth_blank">
                    <label>
                        Повторите пароль
                    </label>
                    <div class="form-block">
                        <input type="password" name="password2">
                        {% if errors.password2 != '' %}
                            <div class="form-error">{{ errors.password2 }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="auth_blank">
                    <label>
                        E-mail
                    </label>
                    <div class="form-block">
                        <input type="email" name="email" value="{{ email }}">
                        {% if errors.email != '' %}
                            <div class="form-error">{{ errors.email }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="auth_blank">
                    <label>
                        Имя
                    </label>
                    <div class="form-block">
                        <input type="text" name="firstname" value="{{ firstname }}">
                        {% if errors.firstname != '' %}
                            <div class="form-error">{{ errors.firstname }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="auth_blank">
                    <label>
                        Фамилия
                    </label>
                    <div class="form-block">
                        <input type="text" name="surname" value="{{ surname }}">
                        {% if errors.surname != '' %}
                            <div class="form-error">{{ errors.surname }}</div>
                        {% endif %}
                    </div>
                </div>
                <br>
                <button type="submit">Зарегистрироваться</button>
                <a style=" font-size: 20px; font-weight: 200; "  href="{% url 'registration2_url' %}">Регистрация через форму</a>
            </div>
        </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/registration2.html
{% extends 'base.html' %}

{% block body1 %}
    <div id="body1">
        <div class="container">
            <div class="row centered">
                <div class="col-lg-8 col-lg-offset-2">
                    <h5><br>Регистрация<br><br></h5>
                </div>
             <form method= "POST">
         <div class="auth_block" style="width: 452px">
                {% csrf_token %}
                {{ form.as_p }}
             <br>
             <button type= "submit"> Зарегистрироваться </button>
         </div>
    </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/success.html
{% extends 'base.html' %}

{% block body1 %}
    <div id="body1">
        <div class="container">
            <div class="row centered">
                <div class="col-lg-8 col-lg-offset-2">
                    <h6><br>Авторизация прошла успешно!<br></h6>
                    <h2>Ещё чуть-чуть, и Вы будете перенаправлены на главную страницу<br></h2>
                    <a style=" font-size: 20px; font-weight: 200; "  href="{% url 'x0_url' %}">Либо нажмите на данную надпись</a>
                    <meta http-equiv="refresh" content="2; url=/db/">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/x0.html
{% extends 'base.html' %}
{% block body1 %}
<link rel="stylesheet" href="http://bootstraptema.ru/plugins/2015/b-v3-3-6/bootstrap.min.css" />
<link rel="stylesheet" href="http://bootstraptema.ru/_sf/2/279_tic-tac-toe.css" />
<br><br><br>
<div class="row centered">
<div class="container" style="width: 500px">
<h1>Пора заняться делом</h1>
<div class="col-xs-12">


<div class="col-md-6">
<div class="clearfix"></div>
 <article class="parent">
 <form>
 <div id="gr">
 <input type="checkbox" id="a1">
 <input type="checkbox" id="a2">
 <input type="checkbox" id="a3">
 <input type="checkbox" id="a4">
 <input type="checkbox" id="a5">
 <input type="checkbox" id="a6">
 <input type="checkbox" id="a7">
 <input type="checkbox" id="a8">
 <input type="checkbox" id="a9">

 <input type="checkbox" id="b1">
 <input type="checkbox" id="b2">
 <input type="checkbox" id="b3">
 <input type="checkbox" id="b4">
 <input type="checkbox" id="b5">
 <input type="checkbox" id="b6">
 <input type="checkbox" id="b7">
 <input type="checkbox" id="b8">
 <input type="checkbox" id="b9">

 <input type="checkbox" id="c1">
 <input type="checkbox" id="c2">
 <input type="checkbox" id="c3">
 <input type="checkbox" id="c4">
 <input type="checkbox" id="c5">
 <input type="checkbox" id="c6">
 <input type="checkbox" id="c7">
 <input type="checkbox" id="c8">
 <input type="checkbox" id="c9">

 <input type="checkbox" id="d1">
 <input type="checkbox" id="d2">
 <input type="checkbox" id="d3">
 <input type="checkbox" id="d4">
 <input type="checkbox" id="d5">
 <input type="checkbox" id="d6">
 <input type="checkbox" id="d7">
 <input type="checkbox" id="d8">
 <input type="checkbox" id="d9">

 <input type="checkbox" id="e1">
 <input type="checkbox" id="e2">
 <input type="checkbox" id="e3">
 <input type="checkbox" id="e4">
 <input type="checkbox" id="e5">
 <input type="checkbox" id="e6">
 <input type="checkbox" id="e7">
 <input type="checkbox" id="e8">
 <input type="checkbox" id="e9">


 <div id="pa">
 <label for="a1" id="aa1">O</label>
 <label for="a2" id="aa2">O</label>
 <label for="a3" id="aa3">O</label>
 <label for="a4" id="aa4">O</label>
 <label for="a5" id="aa5">O</label>
 <label for="a6" id="aa6">O</label>
 <label for="a7" id="aa7">O</label>
 <label for="a8" id="aa8">O</label>
 <label for="a9" id="aa9">O</label>
 </div>

 <div id="pb">
 <label for="b1" id="bb1">O</label>
 <label for="b2" id="bb2">O</label>
 <label for="b3" id="bb3">O</label>
 <label for="b4" id="bb4">O</label>
 <label for="b5" id="bb5">O</label>
 <label for="b6" id="bb6">O</label>
 <label for="b7" id="bb7">O</label>
 <label for="b8" id="bb8">O</label>
 <label for="b9" id="bb9">O</label>
 </div>

 <div id="pc">
 <label for="c1" id="cc1">O</label>
 <label for="c2" id="cc2">O</label>
 <label for="c3" id="cc3">O</label>
 <label for="c4" id="cc4">O</label>
 <label for="c5" id="cc5">O</label>
 <label for="c6" id="cc6">O</label>
 <label for="c7" id="cc7">O</label>
 <label for="c8" id="cc8">O</label>
 <label for="c9" id="cc9">O</label>
 </div>

 <div id="pd">
 <label for="d1" id="dd1">O</label>
 <label for="d2" id="dd2">O</label>
 <label for="d3" id="dd3">O</label>
 <label for="d4" id="dd4">O</label>
 <label for="d5" id="dd5">O</label>
 <label for="d6" id="dd6">O</label>
 <label for="d7" id="dd7">O</label>
 <label for="d8" id="dd8">O</label>
 <label for="d9" id="dd9">O</label>
 </div>

 <div id="pe">
 <label for="e1" id="ee1">O</label>
 <label for="e2" id="ee2">O</label>
 <label for="e3" id="ee3">O</label>
 <label for="e4" id="ee4">O</label>
 <label for="e5" id="ee5">O</label>
 <label for="e6" id="ee6">O</label>
 <label for="e7" id="ee7">O</label>
 <label for="e8" id="ee8">O</label>
 <label for="e9" id="ee9">O</label>
 </div>

 <span id="o1">O</span>
 <span id="o2">O</span>
 <span id="o3">O</span>
 <span id="o4">O</span>
 <span id="o5">O</span>
 <span id="o6">O</span>
 <span id="o7">O</span>
 <span id="o8">O</span>
 <span id="o9">O</span>

 <span id="x1">X</span>
 <span id="x2">X</span>
 <span id="x3">X</span>
 <span id="x4">X</span>
 <span id="x5">X</span>
 <span id="x6">X</span>
 <span id="x7">X</span>
 <span id="x8">X</span>
 <span id="x9">X</span>

 <span id="d1">X</span>
 <span id="d2">X</span>
 <span id="d3">X</span>
 <span id="d4">X</span>
 <span id="d5">X</span>
 <span id="d6">X</span>
 <span id="d7">X</span>
 <span id="d8">X</span>
 <span id="d9">X</span>


 <p id="wx1">I win</p>
 <p id="wx2">I win</p>
 <p id="wx3">I win</p>
 <p id="wx4">I win</p>
 <p id="wx5">I win</p>
 <p id="wx6">I win</p>
 <p id="wx7">I win</p>
 <p id="wx8">I win</p>
 <p id="wx9">I win</p>

 <p id="wd1">draw</p>
 <p id="wd2">draw</p>
 <p id="wd3">draw</p>
 <p id="wd4">draw</p>
 <p id="wd5">draw</p>
 <p id="wd6">draw</p>
 <p id="wd7">draw</p>
 <p id="wd8">draw</p>
 <p id="wd9">draw</p>

 <p id="wo1">You win</p>
 <p id="wo2">You win</p>
 <p id="wo3">You win</p>
 <p id="wo4">You win</p>
 <p id="wo5">You win</p>
 <p id="wo6">You win</p>
 <p id="wo7">You win</p>
 <p id="wo8">You win</p>
 <p id="wo9">You win</p>

 </div>
 <input id="button1" type="reset" value="Новая игра" style="width: 300px">
 </form>
 </article>
<div class="clearfix"></div>
</div>

</div>

</div>
</div>
</div>
{% endblock %}